// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scribe.Data.Database;

#nullable disable

namespace Scribe.Data.Database.Migrations
{
    [DbContext(typeof(ScribeContext))]
    [Migration("20240620120709_FixingDocumentTagAndFolderRelationship")]
    partial class FixingDocumentTagAndFolderRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DocumentTag", b =>
                {
                    b.Property<int>("Document_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Document_id", "TagsName", "TagsFolderId");

                    b.HasIndex("TagsName", "TagsFolderId");

                    b.ToTable("DocumentTag");
                });

            modelBuilder.Entity("Scribe.Data.Model.Document", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.HasIndex("FolderId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Scribe.Data.Model.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NavigationIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Scribe.Data.Model.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name", "FolderId");

                    b.HasIndex("FolderId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DocumentTag", b =>
                {
                    b.HasOne("Scribe.Data.Model.Document", null)
                        .WithMany()
                        .HasForeignKey("Document_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scribe.Data.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsName", "TagsFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scribe.Data.Model.Document", b =>
                {
                    b.HasOne("Scribe.Data.Model.Folder", null)
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scribe.Data.Model.Tag", b =>
                {
                    b.HasOne("Scribe.Data.Model.Folder", null)
                        .WithMany("Tags")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scribe.Data.Model.Folder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
